/**
 * Validation utilities to prevent accidental nginx configuration breaks
 * and injection attacks when user input is passed through the SDK.
 */

/**
 * Validates advanced_config to prevent patterns that would break nginx configuration.
 * This provides basic protection against common mistakes and injection attacks.
 * 
 * Note: These validations are defensive checks to help prevent breaking your nginx config.
 * If you need to use these patterns legitimately, you can bypass validation by directly
 * calling the API.
 */
export function validateAdvancedConfig(config: string | undefined): void {
  if (!config || config.trim() === '') {
    return;
  }

  // Check for patterns that would break out of the server block context
  // These would corrupt the nginx configuration generated by NPM
  const breakoutPatterns = [
    { pattern: /}\s*server\s*{/i, message: 'Closing and opening server blocks would break NPM configuration' },
    { pattern: /}\s*http\s*{/i, message: 'Closing and opening http blocks would break NPM configuration' },
  ];

  for (const { pattern, message } of breakoutPatterns) {
    if (pattern.test(config)) {
      throw new Error(`Invalid advanced_config: ${message}`);
    }
  }
}

/**
 * Validates domain names to prevent characters that would break nginx configuration.
 * Provides basic validation while allowing flexibility for various domain formats.
 * 
 * Supports:
 * - Standard domains: example.com, sub.example.com
 * - Wildcards: *.example.com
 * - Single-label: localhost, myserver
 * - IP addresses: 192.168.1.1 (though not recommended for domain_names)
 * - Unicode/IDN domains (if already in ASCII/punycode form)
 */
export function validateDomainNames(domains: string[] | undefined): void {
  if (!domains || domains.length === 0) {
    return;
  }

  for (const domain of domains) {
    if (!domain || domain.trim() === '') {
      throw new Error('Domain name cannot be empty');
    }

    // Only reject characters that would break nginx config syntax
    // Checks for: space, tab, newline, carriage return, semicolon, braces
    if (/[\s;{}]/.test(domain)) {
      throw new Error(
        `Invalid domain name: "${domain}" contains characters that would break nginx configuration (spaces, semicolons, or braces)`
      );
    }

    // Check reasonable length to prevent issues
    if (domain.length > 253) {
      throw new Error(`Domain name too long: "${domain}" (max 253 characters)`);
    }
  }
}
